<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html"; 
        charset="UTF-8">
    <title>Registration Form</title>
</head>
<body>
    <h3>Registration Form</h3>
    <form method="post" action="<?=$_SERVER['PHP_SELF']?>">
        <table>
        <tr>
            <td>
                <p>User ID</p>
            </td>
            <td>
                <input type="text" maxlength="5" name="newid"
                required/>
            </td>
        </tr>
        <tr>
            <td>
                <p>Last Name</p>
            </td>
            <td>
                <input type="text" maxlength="20" 
                name="lname" required/>
            </td>
        </tr>
        <tr>
            <td>
                <p>First Name</p>
            </td>
            <td>
                <input type="text" maxlength="20"
                name="fname"/>
            </td>
        </tr>
        <tr>
            <td>
                <p>
                    E-Mail Address
                </p>
            </td>
            <td>
                <input type="email" maxlength="20" 
                name="newemail" required/>
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" name="submit" 
                value="Submit"/>
            </td>
        </tr>
        </table>
    </form>
</body>
</html>