<?php echo $this->layout()->content; ?>

<div> <!-- Navigation -->
        <nav>
            <ul>
                <li>Home</li>
                <li>Posts</li>
                <li>About Me</li>
                <li>Login</li>
            </ul>
        </nav>
    </div>

    <div> <!-- Header -->
        <h1>Mandifying Gravity</h1>
        <blockquote>No hate just self-appreciate.</blockquote>
    </div>